name: Github Action

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Archive the project
        run: tar -cvf project.tar .

      - name: Upload the archive as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: project
          path: project.tar
